name: Send Slack notification

on:
  deployment_status:
    types:
      - completed

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ github.event.deployment_status.state }}
          message: 'Deployment of branch ${{ github.event.deployment_status.ref }} completed!'
          webhook_url: ${{ secrets.https://hexa-urf4241.slack.com/archives/C057FQ920AG }}
